"""Image conversion, tensor unnormalization, and disk I/O utilities.

This module provides utility functions for mapping synthetic image tensors
from their training range back to valid pixel ranges, converting them to
PIL Images, and saving batches of images as grids to the file system.
"""

import os
from typing import Union

import torch
import torchvision.utils as vutils
from PIL import Image


def denormalize_tensor(tensor: torch.Tensor) -> torch.Tensor:
    """Map an image tensor from [-1, 1] to [0, 1].

    Args:
        tensor: The input image tensor, typically generated by the cGAN.
            Values are expected to be roughly in the range [-1, 1].

    Returns:
        A new tensor with values mapped and clamped to [0, 1].
    """
    # Map [-1, 1] to [0, 1]
    denorm = (tensor + 1.0) / 2.0
    
    # Clamp safely to ensure valid image range
    return torch.clamp(denorm, 0.0, 1.0)


def tensor_to_pil(tensor: torch.Tensor) -> Image.Image:
    """Convert a single image tensor in [C, H, W] format to a PIL Image.

    Args:
        tensor: Image tensor of shape [C, H, W] with values in [-1, 1] or [0, 1].
            If values are in [-1, 1] (e.g., min < 0), they will be automatically
            denormalized to [0, 1] before conversion.

    Returns:
        A PIL Image object in RGB mode.
        
    Raises:
        ValueError: If the tensor is not 3-dimensional.
    """
    if tensor.dim() != 3:
        raise ValueError(f"Expected a 3D tensor [C, H, W], got {tensor.dim()}D tensor.")

    # Move to CPU and detach from any computation graph
    tensor = tensor.detach().cpu()

    # Automatically denormalize if the tensor appears to be in [-1, 1]
    if tensor.min() < 0.0:
        tensor = denormalize_tensor(tensor)
    else:
        # Just ensure values are clamped properly to [0, 1]
        tensor = torch.clamp(tensor, 0.0, 1.0)

    # Convert to NumPy array with shape [H, W, C] and scale to [0, 255]
    # torch permute: [C, H, W] -> [H, W, C]
    ndarr = tensor.mul(255).add_(0.5).clamp_(0, 255).permute(1, 2, 0).to(torch.uint8).numpy()
    
    return Image.fromarray(ndarr, mode="RGB")


def save_image_grid(
    images: torch.Tensor,
    filepath: str,
    nrow: int = 10,
) -> None:
    """Save a batch of image tensors as a grid to disk.

    Args:
        images: A batch of image tensors of shape [B, C, H, W].
            Values are expected to be in [-1, 1].
        filepath: Destination path where the grid image will be saved.
        nrow: Number of images displayed in each row of the grid.
    """
    if images.dim() != 4:
        raise ValueError(f"Expected a 4D batch tensor [B, C, H, W], got {images.dim()}D tensor.")

    # Move to CPU to prevent device mismatch errors during disk operations
    images = images.detach().cpu()

    # Denormalize images to [0, 1] range for saving
    images = denormalize_tensor(images)

    # Create the parent directory if it does not exist
    directory = os.path.dirname(filepath)
    if directory:
        os.makedirs(directory, exist_ok=True)

    # Save the grid image
    vutils.save_image(images, filepath, nrow=nrow, padding=2, normalize=False)
